### ISSUE TITLE
Some variables are being ignored 

### ISSUE THREAD

**Issue by tchit** [tcrowe/dra-factory#1]
Hi, 
First, very nice script. 
I’m running into an issue though:
When I change WALLETS_COUNT, WALLETS_MAXIMUM_DRA and WALLETS_MAXIMUM_SEND_MASTER, the values I put are being ignored and it still runs with default settings. Any idea how to solve this?
Thanks :)

**Comment by tcrowe** [comment]
Hi @tchit :wave:

In this script most of the lines are commented out but it gives an example using `export WALLETS_COUNT=3` https://github.com/tcrowe/dra-factory/blob/master/mine.sh#L12

Then here it's picking it up from the environment:
https://github.com/tcrowe/dra-factory/blob/master/src/client.ls#L18

Then here it's supposed to do `WALLETS_COUNT or 5`: https://github.com/tcrowe/dra-factory/blob/master/src/client.ls#L110

Are you able to send your script without any private keys and we'll take a look?

**Comment by tcrowe** [comment]
Maybe we can also optimize this script so it works best for the new mining strategy on diruna.

**Comment by tcrowe** [comment]
Thanks for testing that @tchit 

I will try it too! 🤓

**Comment by tchit** [comment]
Regarding adapting the script, there is a 0.5 DRA bonus for each new account. A powerful optimization would be to merge the wallets into new wallets each week, thus creating a new bonus each time.
